version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 12613527
      API_HASH: b3d59e071c9c2358399638e650ae080c
      BOT_TOKEN: 7035051751:AAE9IdqziEABPgJLrIi8hLMlIVZDWBS6Hco
      SESSION: BAAAxJIAIvz5gRfh4slLLqm_86WHIfiMQ9zzzD9CxxUvc4qH-JQlM9tS1bBwdxFYTKb-2lK7vQlzNTufR68j_OXdTmls9sALBGfSOAajARReZh4JjU0V73FRxx9Ut7nSIxoFo7IK1a-yDdtU6cjQ9amAzL5_rl1nrsTkPp8HJ5V9MYLDjczwY0gzjW-3Fm5v-E-R0nM3PeYUuC78nnb2A6CxqAsUtViiAQfq3P_ZJ0kio7G3hLv1eC6oiiiadZzRpGFybByw1DR23jXXVSy-kAku9B8-nSg1xugmoDJCjDJqK5ESeZqVeM1EWQMC-mz4tQQK4N2hnb9JpT4IsuFGfNfn3aGuZwAAAAGFfhU-AA
      AUTH: 6534599998
      FORCESUB: theysaidp
